version: '2'

volumes:
  nextcloud:
  db:

services:
  db:
    image: postgres
    restart: always
    volumes:
      - db:/var/lib/postgresql
    environment:
      - POSTGRES_PASSWORD==N3xtCl0ud!
      - POSTGRES_USER=nextcloud
      - POSTGRES_DB=nextcloud
      - POSTGRES_INITDB_ARGS="--encoding=UTF8 --locale=zh_CN.UTF8"

  app:
    image: nextcloud
    ports:
      - 8081:80
    links:
      - db
    volumes:
      - nextcloud:/var/www/html
    restart: always
